name: Docker Build/Publish Image 

on: 
  push:
    tags:
      - '**' # Run every time a tag is pushed

jobs:   
  build:    
    runs-on: ubuntu-latest
       
    env:      
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE: zlundqvist/cbcbotv5
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:    
    - name: Checkout the code
      uses: actions/checkout@v2

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Prepare      
      if: success()      
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
        echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Run Buildx (push image)      
      if: success()
      run: |        
        docker buildx build \
          --platform ${{ steps.prepare.outputs.docker_platform }} \
          --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
          --file ./Dockerfile \
          --output type=image,push=true .
